source 'https://github.com/CocoaPods/Specs.git'
#source ’https://gitlab.monetplus.cz/AHE_PODS/podspecs.git'
#source 'https://github.com/monetplus/EOP_iOS_Podspecs.git'
source 'https://github.com/Ministerstvo-vnitra/EOP_iOS_podspecs.git'
#source ‘https://gitlab.monetplus.cz/AHE_EOP/BLE-Readers-iOS-Podspecs.git’

use_frameworks!

# disable bitcode for all pod targets bcz miniDriver doesn't ship with bitcode
post_install do |installer|


    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['VALID_ARCHS'] = 'armv7 arm64'
            config.build_settings['ARCHS'] = 'armv7 arm64'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end

target 'apduDemoApp' do
  pod 'GemaltoReader'
  pod 'ACSReader'
  pod 'FeitianReader'
  pod 'R.swift', '5.0.0.alpha.2'
  pod 'Cartography'
  pod 'APDUSDK'

  target 'apduDemoAppTests' do
    inherit! :search_paths
  end
end
